[build]
  functions = "netlify/functions"
  publish = "public"

[dev]
  publish = "public"
  port = 8888
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
