[build]
  functions = "netlify/functions"
  publish = "public"

[dev]
  publish = "public"
  port = 8888
  autoLaunch = false

[[redirects]]
  from = "/pdfs/*"
  to = "/pdfs/:splat"
  status = 200

[[redirects]]
  from = "/texts/*"
  to = "/texts/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*", Content-Type = "text/plain; charset=utf-8" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
