[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  publish = "."
  port = 8888
  autoLaunch = false

[[redirects]]
  from = "/pdfs/*"
  to = "/pdfs/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
