[build]
  functions = "netlify/functions"
  publish = "public"

[dev]
  publish = "public"
  port = 8888
  autoLaunch = false

[[headers]]
  for = "/texts/*"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/texts/*"
  to = "/texts/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false