[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  [functions.timeout]
  external_node_modules = []
  included_files = []
  node_bundler = "esbuild"
  timeout_seconds = 60

[dev]
  publish = "public"
  port = 8888
  autoLaunch = false

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false